### PR TITLE
Log output from imports to a file

### PR DESCRIPTION
**Pull request by tewshi**

### CODE REVIEW

**Comment by tewshi** [comment]
Please check @d-beck

**Comment by d-beck** [comment]
Thanks @tewshi, the results for a successful import look great

I tried running the import with an invalid file ([Manual.Collection.Blank.xlsx](https://github.com/ablestar/ablestar-cli/files/12538100/Manual.Collection.Blank.xlsx)) and I got the following:

image

Instead of raising an error when it fails can we capture the error and include it in the output file?

The command I used to trigger the error is:

```
ablestar-cli import custom_collections xxxxxxxx.myshopify.com --fileName=Manual.Collection.Blank.xlsx --format=Matrixify
```

**Comment by tewshi** [comment]
Please check again @d-beck

**Review by d-beck — APPROVED** [review]
Thanks @tewshi this works great

**Pull request merged**
